name: "commit-master"

on:
  push:
    branches: 
    - 'master'
env: 
    REGIONID: ${region_id}
    FUNCTIONURN: ${function_urn}
    PROJECTID: ${project_id}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2
    #安装JDK1.8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # 完成java项目打包
    - name: build maven project
      run: mvn clean -U package -Dmaven.test.skip 

    # jar包比较大，先上传到OBS
    - name: Upload To Huawei OBS
      uses: huaweicloud/obs-helper@v1.0.0
      id: upload_file_to_obs
      with:
        access_key: ${{ secrets.ACCESSKEY }}
        secret_key: ${{ secrets.SECRETACCESSKEY }}
        region: ${{ env.REGIONID }}
        bucket_name: bucket-test
        operation_type: upload
        local_file_path: target/functionj.jar
        obs_file_path: function/functionj/v1.0.0.1/    

    #通过OBS部署函数
    - name: functiongraph-deploy-action
      uses: huaweicloud/functiongraph-deploy-action@v1.0
      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: https://functiongraph.${{ env.REGIONID }}.myhuaweicloud.com
        project_id: ${{ env.PROJECTID }}
        function_codetype: obs
        function_urn: ${{ env.FUNCTIONURN}}
        function_file: https://bucket-test.obs.${{ env.REGIONID }}.myhuaweicloud.com/function/functionj/v1.0.0.1/functionj.jar