name: "commit-master"

on:
  push:
    branches: 
    - 'master'
env: 
    REGIONID: ${region_id}
    FUNCTIONURN: ${function_urn}
    PROJECTID: ${project_id}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # 完成java项目打包
    - name: build maven project
      run: mvn clean -U package -Dmaven.test.skip 

    - name: functiongraph-deploy-action
      uses: huaweicloud/functiongraph-deploy-action@v1.0
      with:
        ak: ${{ secrets.AK }}
        sk: ${{ secrets.SK }}
        endpoint: https://functiongraph.${{ env.REGIONID }}.myhuaweicloud.com
        project_id: ${{ env.PROJECTID }}
        function_codetype: jar
        function_urn: ${{ env.FUNCTIONURN}}
        function_file: ./target/functionj.jar