name: Deploy-functiongraph-sample1

on:
  push:
    branches: 
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    - name: deploy single function file to huaweicloud functiongraph
      uses: huaweicloud/deploy-functiongraph-action@v1.0.4
      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: cn-north-4
        project_id: 086cd4ee9e00268e2f76c00ea33b6cbe
        function_codetype: file
        function_urn: urn:fss:cn-north-4:086cd4ee9e00268e2f76c00ea33b6cbe:function:default:github-action-sample-func:latest
        function_file: ./python-sample/index.py
