name: Deploy-functiongraph-sample1

on:
  push:
    branches: 
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2
      
    - name: check dist
      run: ls -a -r -l ./python-sample

    - name: deploy single function file to huaweicloud functiongraph
      uses: huaweicloud/deploy-functiongraph-action@v1.0.4
      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: https://functiongraph.cn-north-4.myhuaweicloud.com
        project_id: 086cd4ee9e00268e2f76c00ea33b6cbe
        function_codetype: file
        function_urn: urn:fss:cn-north-4:086cd4ee9e00268e2f76c00ea33b6cbe:function:default:github-action-sample-func:latest
        function_file: ./root-test.py
#       with:
#         ak: ${{ secrets.ACCESSKEY }}
#         sk: ${{ secrets.SECRETACCESSKEY }}
#         endpoint: https://functiongraph.cn-north-4.myhuaweicloud.com
#         project_id: 086cd4ee9e00268e2f76c00ea33b6cbe
#         function_codetype: jar
#         function_urn: urn:fss:cn-north-4:086cd4ee9e00268e2f76c00ea33b6cbe:function:default:github-action-sample-jar:latest
#         function_file: ./java-sample/functionj.jar
